swagger: "2.0"
info:
  version: 1.0.0
  title: "Space"
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /status:
    get:
      description: Restituisce lo stato dell'astronauta indicato
      operationId: getStatus
      parameters:
        - name: id
          in: query
          description: ID dell'astronauta di cui ottenere lo stato
          required: true
          type: integer
      responses:
        200:
          description: stato dell'astronauta
          schema:
            type: boolean
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Imposta il nuovo stato dell'astronauta
      operationId: setStatus
      parameters:
        - name: id
          in: body
          description: Id dell'astronauta
          required: true
          schema:
            $ref: '#/definitions/setStatus'
      responses:
        200:
          description: Specifica se l'operazione è andata a buon fine
          schema:
            type: boolean
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /surname:
    get:
      description: Restituisce tutti gli astronauti che hanno un certo cognome
      operationId: getAstronautsWithSurname
      parameters:
        - name: surname
          in: query
          description: Cognome dell'astronauta
          required: true
          type: string
      responses:
        200:
          description: Elenco degli astronauti
          schema:
            $ref: '#/definitions/astronauts'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  status:
    allOf:
      - $ref: '#/definitions/setStatus'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  setStatus:
    required:
      - id
    properties:
      id:
        type: integer
      status:
        type: boolean
  astronauts:
    required:
      - id
      - firstName
      - lastName
      - isInSpace
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      isInSpace:
        type: boolean
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string